services:
  crawler:
    build: ./crawler/
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data/crawler:/data/crawler
      - ./data/mentions:/data/mentions
      - ./data/coreference:/data/coreference
      - ./data/export:/data/export

  mentions-web:
    build: ./mentions-web/
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data/crawler:/data/crawler
      - ./data/mentions:/data/mentions
      - ./data/coreference:/data/coreference
      - ./data/export:/data/export
    depends_on:
      crawler:
        condition: service_completed_successfully

  grobid-service:
    image: grobid/grobid:0.8.0
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://grobid-service:8070/api/isalive"]
      interval: 30s
      timeout: 10s
      retries: 5

  mentions-pdf:
    build: ./mentions-pdf/
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data/crawler:/data/crawler
      - ./data/mentions:/data/mentions
      - ./data/coreference:/data/coreference
      - ./data/export:/data/export
    depends_on:
      grobid-service:
        condition: service_healthy
      mentions-web:
        condition: service_started

  coreference:
    build: ./coreference/
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data/crawler:/data/crawler
      - ./data/mentions:/data/mentions
      - ./data/coreference:/data/coreference
      - ./data/export:/data/export
    depends_on:
      mentions-web:
        condition: service_completed_successfully
      mentions-pdf:
        condition: service_completed_successfully

  export:
    build: ./export/
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data/crawler:/data/crawler
      - ./data/mentions:/data/mentions
      - ./data/coreference:/data/coreference
      - ./data/export:/data/export
    depends_on:
      coreference:
        condition: service_completed_successfully